run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gofmt
    - goimports
    - revive
    - gosec

linters-settings:
  goimports:
    local-prefixes: github.com/viniciusfranca/vdt

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
